# Dockerfile
FROM python:3.12-slim

# Install git (required for git+ in requirements.txt)
RUN apt-get update && apt-get install -y --no-install-recommends git ffmpeg && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements_iptv_recorder.txt .
RUN pip install --no-cache-dir -r requirements_iptv_recorder.txt

COPY iptv_recorder.py .

CMD ["python", "-u", "iptv_recorder.py"]
