FROM python:3.12-slim

RUN apt-get update && apt-get install -y openvpn

WORKDIR /app

COPY requirements_vpn_manager.txt .
RUN pip install --no-cache-dir -r requirements_vpn_manager.txt

COPY vpn_manager.py .

CMD ["python", "vpn_manager.py"]
